# Lab Task 01

Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

Concatenate two NumPy arrays horizontally and vertically.

In [7]:
import numpy as np
import pandas as pd

In [5]:
# Reshape
arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr_2d = arr_1d.reshape((3, 4))

print("Reshaped 2D array:")
print(arr_2d)

Reshaped 2D array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [4]:
arr_a = np.array([[1, 2, 3], [4, 5, 6]])
arr_b = np.array([[7, 8, 9], [10, 11, 12]])

# Concatenate horizontally using np.hstack
concatenated_horizontal = np.hstack((arr_a, arr_b))

# Concatenate vertically using np.vstack
concatenated_vertical = np.vstack((arr_a, arr_b))

print("Concatenated horizontally:")
print(concatenated_horizontal)

print("\nConcatenated vertically:")
print(concatenated_vertical)

Concatenated horizontally:
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]

Concatenated vertically:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# Lab Task 02


## Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [14]:
def classify_emails(emails):
    important_keywords = ["urgent", "important", "action required", "critical", "reminder"]
    promotions_keywords = ["deal", "offer", "discount", "promotion"]
    spam_keywords = ["lottery", "free", "click here", "unsubscribe"]

    important_emails = []
    promotions_emails = []
    spam_emails = []

    for email in emails:
        lower_case_email = email.lower()
        
        if any(keyword in lower_case_email for keyword in important_keywords):
            important_emails.append(email)
        elif any(keyword in lower_case_email for keyword in promotions_keywords):
            promotions_emails.append(email)
        elif any(keyword in lower_case_email for keyword in spam_keywords):
            spam_emails.append(email)

    return important_emails, promotions_emails, spam_emails

# Example usage
sample_emails = [
    "URGENT: Action required on your account",
    "Special promotion - 30% off on selected items!",
    "Congratulations! You've won $100 in lottery!",
    "This is a reminder about tomorrow's meeting",
    "Limited-time offer: Buy one, get one free"
]

important, promotions, spam = classify_emails(sample_emails)

print("Important Emails:")
print(important)

print("\nPromotions Emails:")
print(promotions)

print("\nSpam Emails:")
print(spam)

Important Emails:
['URGENT: Action required on your account', "This is a reminder about tomorrow's meeting"]

Promotions Emails:
['Special promotion - 30% off on selected items!', 'Limited-time offer: Buy one, get one free']

Spam Emails:
["Congratulations! You've won $100 in lottery!"]


# Lab Task 03

## English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [3]:
english_spanish_dict = {
    'hello': 'hola',
    'goodbye': 'adiós',
    'cat': 'gato',
    'dog': 'perro',
    'house': 'casa',
    'friend': 'amigo',
    'family': 'familia',
    'book': 'libro',
    'school': 'escuela',
    'computer': 'computadora',
    'internet': 'internet',
    'love': 'amor',
    'city': 'ciudad',
    'country': 'país',
    'food': 'comida',
    'water': 'agua',
    'sun': 'sol',
    'moon': 'luna',
    'bye' : 'ciao'
}

def translate_word(word):
    if word in english_spanish_dict:
        return english_spanish_dict[word]
    else:
        return None

print("Welcome to the English-Spanish Dictionary!")

while True:
    user_input = input("\nEnter an English word (or type 'exit' to quit): ").lower()

    if user_input == 'exit':
        print("Goodbye! Exiting the dictionary.")
        break

    translation = translate_word(user_input)

    if translation:
        print(f"The Spanish translation of '{user_input}' is: {translation}")
    else:
        print(f"Sorry, the translation for '{user_input}' is not available.")


Welcome to the English-Spanish Dictionary!

Enter an English word (or type 'exit' to quit): bye
The Spanish translation of 'bye' is: ciao

Enter an English word (or type 'exit' to quit): exit
Goodbye! Exiting the dictionary.


# Lab Task 04

dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

Some tree example

In [8]:
url = "https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv"
df = pd.read_csv(url)
df

Rank                                              Name Platform  \
0          1                                        Wii Sports      Wii   
1          2                                 Super Mario Bros.      NES   
2          3                                    Mario Kart Wii      Wii   
3          4                                 Wii Sports Resort      Wii   
4          5                          Pokemon Red/Pokemon Blue       GB   
...      ...                                               ...      ...   
16593  16596                Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                     Men in Black II: Alien Escape       GC   
16595  16598  SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                        Know How 2       DS   
16597  16600                                  Spirits & Spells      GBA   

         Year         Genre   Publisher  NA_Sales  EU_Sales  JP_Sales  \
0      2006.0        Sports    Nintendo     41.49     29.02      3.77   
1      1985.0      Platform    Nintendo     29.08      3.58      6.81   
2      2008.0        Racing    Nintendo     15.85     12.88      3.79   
3      2009.0        Sports    Nintendo     15.75     11.01      3.28   
4      1996.0  Role-Playing    Nintendo     11.27      8.89     10.22   
...       ...           ...         ...       ...       ...       ...   
16593  2002.0      Platform       Kemco      0.01      0.00      0.00   
16594  2003.0       Shooter  Infogrames      0.01      0.00      0.00   
16595  2008.0        Racing  Activision      0.00      0.00      0.00   
16596  2010.0        Puzzle    7G//AMES      0.00      0.01      0.00   
16597  2003.0      Platform     Wanadoo      0.01      0.00      0.00   

       Other_Sales  Global_Sales  
0             8.46         82.74  
1             0.77         40.24  
2             3.31         35.82  
3             2.96         33.00  
4             1.00         31.37  
...            ...           ...  
16593         0.00          0.01  
16594         0.00          0.01  
16595         0.00          0.01  
16596         0.00          0.01  
16597         0.00          0.01  

[16598 rows x 11 columns]

In [9]:
total_global_sales = df['Global_Sales'].sum()
print("Total Global Sales for all games:", total_global_sales)

Total Global Sales for all games: 8920.44


In [10]:
highest_sales_game = df.loc[df['Global_Sales'].idxmax()]
print("Game with the highest global sales:")
print(highest_sales_game[['Name', 'Global_Sales']])

Game with the highest global sales:
Name            Wii Sports
Global_Sales         82.74
Name: 0, dtype: object


In [11]:
average_sales_by_region = df[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].mean()
print("Average Sales for each region:")
print(average_sales_by_region)

Average Sales for each region:
NA_Sales       0.264667
EU_Sales       0.146652
JP_Sales       0.077782
Other_Sales    0.048063
dtype: float64


In [12]:
top_genres_global_sales = df.groupby('Genre')['Global_Sales'].sum().nlargest(5)
print("Top 5 Game Genres based on Global Sales:")
print(top_genres_global_sales)

Top 5 Game Genres based on Global Sales:
Genre
Action          1751.18
Sports          1330.93
Shooter         1037.37
Role-Playing     927.37
Platform         831.37
Name: Global_Sales, dtype: float64


In [13]:
total_sales_by_genre_region = df.groupby(['Genre'])[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].sum()
most_popular_genre_na = total_sales_by_genre_region['NA_Sales'].idxmax()
print("Total Sales for each genre in each region:")
print(total_sales_by_genre_region)
print("\nMost Popular Genre in North America (NA_Sales):", most_popular_genre_na)

Total Sales for each genre in each region:
              NA_Sales  EU_Sales  JP_Sales  Other_Sales
Genre                                                  
Action          877.83    525.00    159.95       187.38
Adventure       105.80     64.13     52.07        16.81
Fighting        223.59    101.32     87.35        36.68
Misc            410.24    215.98    107.76        75.32
Platform        447.05    201.63    130.77        51.59
Puzzle          123.78     50.78     57.31        12.55
Racing          359.42    238.39     56.69        77.27
Role-Playing    327.28    188.06    352.31        59.61
Shooter         582.60    313.27     38.28       102.69
Simulation      183.31    113.38     63.70        31.52
Sports          683.35    376.85    135.37       134.97
Strategy         68.70     45.34     49.46        11.36

Most Popular Genre in North America (NA_Sales): Action


In [14]:
df.tail(10)

Rank                                               Name Platform  \
16588  16591                                   Mega Brain Boost       DS   
16589  16592  Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...      PSV   
16590  16593  Eiyuu Densetsu: Sora no Kiseki Material Collec...      PSP   
16591  16594                                Myst IV: Revelation       PC   
16592  16595                                           Plushees       DS   
16593  16596                 Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                      Men in Black II: Alien Escape       GC   
16595  16598   SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                         Know How 2       DS   
16597  16600                                   Spirits & Spells      GBA   

         Year         Genre              Publisher  NA_Sales  EU_Sales  \
16588  2008.0        Puzzle  Majesco Entertainment      0.01      0.00   
16589  2016.0        Action        dramatic create      0.00      0.00   
16590  2007.0  Role-Playing     Falcom Corporation      0.00      0.00   
16591  2004.0     Adventure                Ubisoft      0.01      0.00   
16592  2008.0    Simulation              Destineer      0.01      0.00   
16593  2002.0      Platform                  Kemco      0.01      0.00   
16594  2003.0       Shooter             Infogrames      0.01      0.00   
16595  2008.0        Racing             Activision      0.00      0.00   
16596  2010.0        Puzzle               7G//AMES      0.00      0.01   
16597  2003.0      Platform                Wanadoo      0.01      0.00   

       JP_Sales  Other_Sales  Global_Sales  
16588      0.00          0.0          0.01  
16589      0.01          0.0          0.01  
16590      0.01          0.0          0.01  
16591      0.00          0.0          0.01  
16592      0.00          0.0          0.01  
16593      0.00          0.0          0.01  
16594      0.00          0.0          0.01  
16595      0.00          0.0          0.01  
16596      0.00          0.0          0.01  
16597      0.00          0.0          0.01

In [15]:
top_platforms_global_sales = df.groupby('Platform')['Global_Sales'].sum().nlargest(3)
print("Top 3 Gaming Platforms with the highest Global Sales:")
print(top_platforms_global_sales)

Top 3 Gaming Platforms with the highest Global Sales:
Platform
PS2     1255.64
X360     979.96
PS3      957.84
Name: Global_Sales, dtype: float64


In [16]:
total_global_sales = df['Global_Sales'].sum()
market_share_by_genre = (df.groupby('Genre')['Global_Sales'].sum() / total_global_sales) * 100
print("Market Share for each genre:")
print(market_share_by_genre)

Market Share for each genre:
Genre
Action          19.631094
Adventure        2.679688
Fighting         5.032375
Misc             9.079821
Platform         9.319832
Puzzle           2.745941
Racing           8.206322
Role-Playing    10.396012
Shooter         11.629135
Simulation       4.396644
Sports          14.920004
Strategy         1.963132
Name: Global_Sales, dtype: float64


In [17]:
correlation_coefficient = df['NA_Sales'].corr(df['EU_Sales'])
print("Correlation Coefficient between NA_Sales and EU_Sales:", correlation_coefficient)

Correlation Coefficient between NA_Sales and EU_Sales: 0.7677267483702636
